version: "3.9"
services:
  music:
    build:
      dockerfile: Dockerfile
    environment:
      STRING_SESSION: $STRING_SESSION
      STRING_SESSION2: $STRING_SESSION2
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
